package com.example.mealmates.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF3E69FE)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDDE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001453)
val md_theme_light_secondary = Color(0xFFB0C1FC)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF9F9FF)
val md_theme_light_onSecondaryContainer = Color(0xFF1E1F2E)
val md_theme_light_tertiary = Color(0xFFE2E2E2)
val md_theme_light_onTertiary = Color(0xFF7A7A7A)
val md_theme_light_tertiaryContainer = Color(0xFFE2DFFF)
val md_theme_light_onTertiaryContainer = Color(0xFF0E006A)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FDFF)
val md_theme_light_onBackground = Color(0xFF001F25)
val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F25)
val md_theme_light_surfaceVariant = Color(0xFFE2E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF45464F)
val md_theme_light_outline = Color(0xFF767680)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFFB8C4FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF1A4EE4)
val md_theme_light_outlineVariant = Color(0xFFC6C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFB8C4FF)
val md_theme_dark_onPrimary = Color(0xFF002584)
val md_theme_dark_primaryContainer = Color(0xFF0037B8)
val md_theme_dark_onPrimaryContainer = Color(0xFFDDE1FF)
val md_theme_dark_secondary = Color(0xFFC2C5DD)
val md_theme_dark_onSecondary = Color(0xFF2C2F42)
val md_theme_dark_secondaryContainer = Color(0xFF424659)
val md_theme_dark_onSecondaryContainer = Color(0xFFDEE1F9)
val md_theme_dark_tertiary = Color(0xFFC2C1FF)
val md_theme_dark_onTertiary = Color(0xFF1D05A2)
val md_theme_dark_tertiaryContainer = Color(0xFF372FB7)
val md_theme_dark_onTertiaryContainer = Color(0xFFE2DFFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF45464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C5D0)
val md_theme_dark_outline = Color(0xFF90909A)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF1A4EE4)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB8C4FF)
val md_theme_dark_outlineVariant = Color(0xFF45464F)
val md_theme_dark_scrim = Color(0xFF000000)

val text_colour = Color(0xff0E3057)
val container_colour = Color(0xffF1F5FF)
val star_color = Color(0xffF3B807)

val selectableList_colour = Color(0xffF9F9F9)

val seed = Color(0xFF3561F6)

val background_colour = Color.White
val component_colour = Color(0xFFE4E4E6)
val primary_text_colour = Color(0xFF03174b)
val tertiary_text_colour = Color(0xFFB0B0B0)
val error_colour = Color(0xFFFF5449)
val button_colour = Color(0xff7f4d7a)
val on_button_colour = Color.White
val completed_colour = Color(0xFF195A1C)
